import type { SessionPhase } from "@/lib/phases";
import { SessionState } from "@/lib/tauri";

const now = Date.now();

type MockSession = Omit<SessionState, "phase"> & { phase: SessionPhase };

export const MOCK_SESSIONS: MockSession[] = [
  {
    session_id: "mock-idle-1",
    cwd: "/Users/dev/projects/api-server",
    project_name: "api-server",
    phase: "idle",
    tool_name: null,
    tool_input: null,
    tool_use_id: null,
    pid: 12001,
    color_index: 0,
    last_activity: now - 120000,
  },
  {
    session_id: "mock-processing-1",
    cwd: "/Users/dev/projects/web-app",
    project_name: "web-app",
    phase: "processing",
    tool_name: "Read",
    tool_input: null,
    tool_use_id: null,
    pid: 12002,
    color_index: 1,
    last_activity: now - 5000,
  },
  {
    session_id: "mock-approval-1",
    cwd: "/Users/dev/projects/claude-house",
    project_name: "claude-house",
    phase: "waiting_for_approval",
    tool_name: "Bash",
    tool_input: '{"command": "npm run build"}',
    tool_use_id: "tool-approval-001",
    pid: 12003,
    color_index: 2,
    last_activity: now - 2000,
  },
  {
    session_id: "mock-input-1",
    cwd: "/Users/dev/projects/ml-pipeline",
    project_name: "ml-pipeline",
    phase: "waiting_for_input",
    tool_name: null,
    tool_input: null,
    tool_use_id: null,
    pid: 12004,
    color_index: 3,
    last_activity: now - 30000,
  },
  {
    session_id: "mock-compacting-1",
    cwd: "/Users/dev/projects/data-viz",
    project_name: "data-viz",
    phase: "compacting",
    tool_name: null,
    tool_input: null,
    tool_use_id: null,
    pid: 12005,
    color_index: 4,
    last_activity: now - 10000,
  },
  {
    session_id: "mock-processing-2",
    cwd: "/Users/dev/projects/auth-service",
    project_name: "auth-service",
    phase: "processing",
    tool_name: "Edit",
    tool_input: null,
    tool_use_id: null,
    pid: 12006,
    color_index: 5,
    last_activity: now - 8000,
  },
  {
    session_id: "mock-approval-2",
    cwd: "/Users/dev/projects/infra",
    project_name: "infra",
    phase: "waiting_for_approval",
    tool_name: "Write",
    tool_input: '{"file_path": "/tmp/config.yaml", "content": "key: value"}',
    tool_use_id: "tool-approval-002",
    pid: 12007,
    color_index: 6,
    last_activity: now - 1000,
  },
  {
    session_id: "mock-ended-1",
    cwd: "/Users/dev/projects/legacy",
    project_name: "legacy",
    phase: "ended",
    tool_name: null,
    tool_input: null,
    tool_use_id: null,
    pid: null,
    color_index: 7,
    last_activity: now - 600000,
  },
];
