import { ui } from "@/constants/glyph";

export const CALLOUT_ICONS_MAP: Record<string, string> = {
  abstract: ui.abstract,
  summary: ui.summary,
  tldr: ui.tldr,
  todo: ui.todo,
  info: ui.info,
  success: ui.success,
  check: ui.check,
  done: ui.done,
  question: ui.question,
  help: ui.help,
  faq: ui.faq,
  failure: ui.failure,
  fail: ui.fail,
  missing: ui.missing,
  danger: ui.danger,
  error: ui.error,
  bug: ui.bug,
  example: ui.example,
  quote: ui.quote,
  cite: ui.cite,
  hint: ui.hint,
  attention: ui.attention,
  note: ui.note,
  tip: ui.tip,
  important: ui.important,
  warning: ui.warning,
  caution: ui.caution,
};
