export const ui = {
  neovim: "",
  gitBranch: "",
  gear: "",
  folder_close: "󰉋",
  folder_open: "",
  package: "",
  cursor: "",
  close: "",
  git: "",
  fileTree: "󰙅",
  abstract: "󱉫",
  summary: "󱉫",
  tldr: "󱉫",
  todo: "",
  info: "",
  success: "󰗠",
  check: "󰗠",
  done: "󰗠",
  question: "󰋗",
  help: "󰋗",
  faq: "󰋗",
  failure: "󰅙",
  fail: "󰅙",
  missing: "󰅙",
  danger: "",
  error: "",
  bug: "",
  example: "󱖫",
  quote: "",
  cite: "",
  hint: "",
  attention: "",
  note: "󰋽",
  tip: "",
  important: "",
  warning: "",
  caution: "󰳦",
  none: " ",
  h1: "󰼏",
  h2: "󰎨",
  h3: "󰼑",
  h4: "󰎲",
  h5: "󰼓",
  h6: "󰎴",
  palette: "",
  search: "",
  percent: "󰏰",
  keyboard: "󰌌",
  lightbulb: "",
  github: "",
  checked: "󰄲",
  unchecked: "",
  link: "󰌷",
  copy: "",
  date: "󰃭",
  author: "",
  tag: "",
  category: "",
  title: "󰗴",
  breadcrumb: "󰜢",
  heading: "",
  dark: "󰖔",
  light: "󰖙",
  box: "󱓻",
  minimize: "󰖰",
  bubble_waiting_for_approval: "󱈸",
  bubble_waiting_for_input: "",
  oct_square_fill: "",
  eye: "",
  project: "",
  agent: "󰚩",
  token: "󰍛",
};

export const extensions = {
  // --- Core: source code ---
  Dockerfile: { icon: "󰡨", color: "#2496ed", name: "Dockerfile" },

  // Web/Node
  js: { icon: "", color: "#ffca27", name: "Js" },
  jsx: { icon: "", color: "#44B0CC", name: "Jsx" },
  ts: { icon: "󰛦", color: "#0088d1", name: "Ts" },
  tsx: { icon: "", color: "#44B0CC", name: "Tsx" },
  mjs: { icon: "", color: "#ffca27", name: "Mjs" },

  // Styles / Markup
  css: { icon: "", color: "#1572B6", name: "CSS" },
  scss: { icon: "", color: "#CC6699", name: "Scss" },
  sass: { icon: "", color: "#CC6699", name: "Sass" },
  less: { icon: "", color: "#1D365D", name: "Less" },
  styl: { icon: "", color: "#8DC149", name: "Styl" },
  html: { icon: "", color: "#E06C75", name: "Html" },
  htm: { icon: "", color: "#E06C75", name: "Htm" },
  md: { icon: "", color: "#53B1EB", name: "Md" },
  markdown: { icon: "", color: "#53B1EB", name: "Markdown" },
  mdx: { icon: "", color: "#519ABA", name: "Mdx" },
  xml: { icon: "󰗀", color: "#e37933", name: "Xml" },
  xib: { icon: "󰗀", color: "#e37933", name: "XibXml" },

  // Config / Data
  json: { icon: "", color: "#e5c07b", name: "Json" },
  jsonc: { icon: "", color: "#e5c07b", name: "Jsonc" },
  json5: { icon: "", color: "#e5c07b", name: "Json5" },
  yaml: { icon: "󰈚", color: "#FA6F42", name: "Yaml" },
  yml: { icon: "󰈚", color: "#FA6F42", name: "Yml" },
  toml: { icon: "", color: "#42a5f5", name: "Toml" },
  ini: { icon: "", color: "#6D8086", name: "Ini" },

  // API / Query
  http: { icon: "", color: "#008EC7", name: "HTTP" },
  hurl: { icon: "", color: "#D446A0", name: "Hurl" },
  graphql: { icon: "", color: "#E535AB", name: "GraphQL" },
  gql: { icon: "", color: "#E535AB", name: "GraphQL" },
  sql: { icon: "", color: "#00758F", name: "Sql" },
  prisma: { icon: "󰔶", color: "#2D3748", name: "Prisma" },

  // Scripts / Shell
  sh: { icon: "", color: "#ff7043", name: "Sh" },
  bash: { icon: "", color: "#768495", name: "Bash" },
  zsh: { icon: "", color: "#89e051", name: "Zsh" },
  fish: { icon: "", color: "#40a0d5", name: "Fish" },
  ansi: { icon: "", color: "#89e051", name: "Ansi" },
  ps1: { icon: "󰨊", color: "#012456", name: "PsScriptfile" },
  bat: { icon: "", color: "#C1F12E", name: "Bat" },
  awk: { icon: "", color: "#4D5A5E", name: "Awk" },
  makefile: { icon: "", color: "#6D8086", name: "Makefile" },
  gnumakefile: { icon: "", color: "#6D8086", name: "Makefile" },
  mk: { icon: "", color: "#6D8086", name: "Makefile" },
  gradle: { icon: "", color: "#02303A", name: "Gradle" },
  bazel: { icon: "", color: "#89E051", name: "Bazel" },
  bzl: { icon: "", color: "#89E051", name: "Bzl" },

  // Languages
  go: { icon: "", color: "#00ADD8", name: "Go" },
  rs: { icon: "", color: "#FA6F42", name: "Rs" },
  rust: { icon: "", color: "#FA6F42", name: "Rust" },
  py: { icon: "", color: "#3776AB", name: "Py" },
  python: { icon: "", color: "#3776AB", name: "Python" },
  rb: { icon: "", color: "#CC342D", name: "Rb" },
  php: { icon: "", color: "#777BB4", name: "Php" },
  java: { icon: "", color: "#007396", name: "Java" },
  kt: { icon: "", color: "#7F52FF", name: "Kotlin" },
  kts: { icon: "", color: "#7F52FF", name: "KotlinScript" },
  scala: { icon: "", color: "#DC322F", name: "Scala" },
  hs: { icon: "", color: "#5E5086", name: "Hs" },
  lua: { icon: "", color: "#53b1eb", name: "Lua" },
  nix: { icon: "", color: "#5277C3", name: "Nix" },
  nu: { icon: "", color: "#3AA675", name: "Nushell" },

  ml: { icon: "λ", color: "#E37933", name: "Ml" },
  mli: { icon: "λ", color: "#E37933", name: "Mli" },
  swift: { icon: "", color: "#FA7343", name: "Swift" },

  // C/C++ headers
  h: { icon: "", color: "#A074C4", name: "H" },
  hh: { icon: "", color: "#A074C4", name: "Hh" },
  hpp: { icon: "", color: "#A074C4", name: "Hpp" },
  hxx: { icon: "", color: "#A074C4", name: "Hxx" },

  // Framework / Special
  svelte: { icon: "", color: "#FF3E00", name: "Svelte" },
  vue: { icon: "󰡄", color: "#41B883", name: "Vue" },
  astro: { icon: "", color: "#FF5D01", name: "Astro" },
  heex: { icon: "", color: "#A074C4", name: "Heex" },
  leex: { icon: "", color: "#A074C4", name: "Leex" },
  "blade.php": { icon: "", color: "#F05340", name: "Blade" },

  // Tooling / Misc
  vim: { icon: "", color: "#019833", name: "Vim" },
  log: { icon: "󰌱", color: "#AAAAAA", name: "Log" },
  lock: { icon: "", color: "#BBBBBB", name: "Lock" },
  lck: { icon: "", color: "#BBBBBB", name: "Lock" },
  license: { icon: "󰿃", color: "#ff5722", name: "License" },
  txt: { icon: "󰈙", color: "#AAAAAA", name: "Txt" },
  plaintext: { icon: "󰈙", color: "#98c379", name: "text" },
  text: { icon: "󰈙", color: "#5ee051", name: "text" },
  git: { icon: "", color: "#F14C28", name: "GitLogo" },
  webpack: { icon: "󰜫", color: "#1C78C0", name: "Webpack" },
  wasm: { icon: "", color: "#624DE8", name: "Wasm" },
  diff: { icon: "", color: "#624DE8", name: "Diff" },
};
